[build-system]
requires = ["flit_core>=3.12.0,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ansys-api-result-explorer"
version = "0.1.0"
description = "Result Explorer gRPC Interface Package."
requires-python = ">=3.10,<4"
authors = [{ name = "ANSYS, Inc."}]
maintainers = [{ name = "ANSYS, Inc."}]
repository = "https://github.com/ansys/ansys-api-result-explorer"
classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
    "protobuf<8",
    "grpcio",
]

[dependency-groups]
dev = [
    "pytest==9.0.3",
    "pytest-cov==7.1.0",
    "pre-commit==4.6.0",
]

build = [
    "requests",
    "mypy-protobuf",
    "grpcio-tools",
]

[tool.uv]
default-groups = ["dev"]
cache-dir = "./.uv_cache"

[project.urls]
Source = "https://github.com/ansys/ansys-api-result-explorer"
Homepage = "https://github.com/ansys/ansys-api-result-explorer"
Tracker = "https://github.com/ansys/ansys-api-result-explorer/issues"

[tool.flit.module]
name = "ansys.api.result_explorer"

[tool.ruff.lint]
select = ["E", "F", "UP", "N", "C4", "I", "W", "B006", "B015", "B904"]
ignore = ["E711", "E501"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "[%(asctime)s | %(levelname)s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
filterwarnings = [
    "ignore::DeprecationWarning",
]
junit_family = "xunit2"