[build-system]
build-backend = "flit_core.buildapi"
requires = [ "flit-core>=3.12.0,<5" ]

[project]
name = "ansys-api-result-explorer"
version = "0.1.1"
description = "Result Explorer gRPC Interface Package."
readme = "README.md"
license = "Apache-2.0"
license-files = [ "LICENSE" ]
maintainers = [ { name = "Synopsys, Inc. and ANSYS, Inc." } ]
authors = [ { name = "Synopsys, Inc. and ANSYS, Inc." } ]
requires-python = ">=3.10,<4"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "grpcio",
  "protobuf<7",
]
urls.Documentation = "https://github.com/ansys/ansys-api-result-explorer#readme"
urls.Homepage = "https://github.com/ansys/ansys-api-result-explorer"
urls.Issues = "https://github.com/ansys/ansys-api-result-explorer/issues"
urls.Releases = "https://github.com/ansys/ansys-api-result-explorer/releases"
urls.Source = "https://github.com/ansys/ansys-api-result-explorer"

[dependency-groups]
dev = [
  "pre-commit==4.6.2",
  "pytest==9.1.1",
  "pytest-cov==7.1.0",
]
build = [
  "ansys-tools-protoc-helper>=0.7.0",
  "requests",
]

[tool.flit]
module.name = "ansys.api.result_explorer"

[tool.uv]
default-groups = [ "dev" ]
cache-dir = "./.uv_cache"

[tool.ruff]
lint.select = [ "B006", "B015", "B904", "C4", "E", "F", "I", "N", "UP", "W" ]
lint.ignore = [ "E501", "E711" ]
lint.per-file-ignores."__init__.py" = [ "F401" ]

[tool.pytest]
ini_options.filterwarnings = [
  "ignore::DeprecationWarning",
]
ini_options.log_cli = true
ini_options.log_cli_level = "DEBUG"
ini_options.log_cli_format = "[%(asctime)s | %(levelname)s] %(message)s (%(filename)s:%(lineno)s)"
ini_options.log_cli_date_format = "%Y-%m-%d %H:%M:%S"
ini_options.junit_family = "xunit2"
