name: Update server models

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight

env:
  MAIN_PYTHON_VERSION: '3.11'

jobs:

  update:
    name: "Update server models"
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          enable-cache: "false"

      - name: Start Result Explorer
        id: rx-compose
        uses: ansys-internal/pyresultexplorer/.github/actions/result-explorer-docker@main
        with:
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          ghcr-username: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          ghcr-token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          license-server: ${{ secrets.LICENSE_SERVER }}

      - name: Generate server models from openapi
        run: |
          python scripts/generate_proto_from_openapi.py

      - name: "Create PR if changes detected"
        id: create-pr
        uses: peter-evans/create-pull-request@v8
        with:
          title: "[Auto] Update server models"
          base: main
          branch: maint/update-server-models
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          delete-branch: true
          body: |
            This PR was automatically generated by a workflow to update the server models.
            Please review the changes and merge if everything looks good.
